### ISSUE TITLE
Next/Previous button doesn't work

### ISSUE THREAD

**Issue by tongnk** [milgra/highsierramediakeyenabler#7] opened 2017-11-16 00:51 UTC
Using spotify - when I press the next/previous button it doesn't skip to the next/previous song. Play button works as expected. 

Seems to work on the mac keyboard itself but on an external one (have a daas) the behaviour above occurs

**Comment by keevvinc** [comment] 2017-11-20 09:15
It does work for me. Weird

**Comment by scporse** [comment] 2017-11-20 09:25
@keevvinc 
Maybe you're not using an external keyboard?
I'm having the same issue as OP, and am using an external Apple USB-keyboard (with Danish/nordic layout - although I suppose that is not really of importance).

**Comment by keevvinc** [comment] 2017-11-20 09:25
Oh, indeed - i am using internal keyboard.

**Comment by milgra** [comment] 2017-11-29 12:48
I will check the issue as soon as I can get an external keyboard.

**Comment by spacerodent** [comment] 2017-12-04 22:55
I can confirm on OSX 10.13.1 with ITunes 12.7.1.14 the next/previous buttons don't work. I am willing to send you an external keyboard (I have multiple ones in my closet) so you can work on this issue if you send me your mailing address.

**Comment by milgra** [comment] 2017-12-05 17:57
Hi, thank you very much but I also have a few at my workplace - I will check the problem as soon as I will have time.

**Comment by pgsil** [comment] 2017-12-26 10:28
Still experiencing this issue on my end and with the latest version of the app.

**Comment by sh1217sh** [comment] 2017-12-27 13:11
@milgra 
I've created a PR fixing this issue. Please review it.

**Comment by milgra** [comment] 2017-12-27 15:33
PR is accepted & merged, please check out the latest version.

**Comment by eyeofthefrog** [comment] 2018-01-19 01:26
If there's a compiled version, I'll take it for a spin.

**Comment by sh1217sh** [comment] 2018-01-25 17:37
@eyeofthefrog 
You can find the compiled version on the owner's blog. Link is in the readme file.

**Comment by eyeofthefrog** [comment] 2018-01-25 17:59
@sh1217sh I see, it's a little confusing since it doesn't give a build date on the blog....wasn't aware that was new. It works with my bluetooth Logitech K380. Thanks for the fix!

**Closed** 2018-01-30 09:55 UTC
