### ISSUE TITLE
doesn't work with Airpod

### ISSUE THREAD

**Issue by quangvh23** [milgra/highsierramediakeyenabler#16] opened 2017-12-16 11:01 UTC
Take out 1 piece of Airpod doesn't stop the music despite "Automatic Ear Detection" enabled.
Take out both pieces of Airpod make the Mac use the speaker, which is really annoying.

**Comment by alejandroivan** [comment] 2017-12-21 03:02
As stated in the repo description, this app works with physical buttons. No Touch Bar or Airpods are supported (but if you can add that functionality, I would assume you can pull request your updates).

**Comment by joaodforce** [comment] 2018-03-15 17:14
Duplicate of #19

**Comment by milgra** [comment] 2018-04-10 08:49
This is a behaviour of MacOS I cannot change :(

**Closed by milgra** 2018-04-10 08:49 UTC
